### ISSUE TITLE
Cypress CI intermittent issue

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#181]
Cypress CI, appears to have an intermittent where occasionally it fails to expand the source tree and select the "todo-view" file. 

```
node_modules/.bin/cypress ci e09e86a1-8468-4a14-97ce-7b289a680a8f


Tests should begin momentarily...



  Todo MVC

    1) Adding Breakpoints in one source

    2) "after each" hook


  0 passing (13s)
  2 failing

  1) Todo MVC Adding Breakpoints in one source:
     CypressError: Timed out retrying: Expected to find content: 'examples' within the selector: '.node' but never did.
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4678:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4642:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4670:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5589:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7607:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  2) Todo MVC "after each" hook:
     CypressError: Timed out retrying: Expected to find content: 'examples' within the selector: '.node' but never did.
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4678:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4642:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4670:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5589:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7607:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)
```

**Comment by jasonLaster** [comment]
We've had four issues this past week:

1) incorrect project ID - this is fixed. I accidentally changed the key when looking into the header issue.
2) Header - this is fixed. It was a short lived regression when cypress went from 0.15.x to 0.16
3) no tabs - this is fixed. There's an infrequent race condition between loading todomvc in firefox and loading the debugger. I fixed it by adding a one second sleep. The issue is in selenium knowing when todomvc is loaded and we can have a better fix.
4) source tree is not populated. This is not yet fixed. I believe the problem occurs when firefox sends network events, which might slow down the new source events. I'll look into this more, but it should be infrequent.

**Comment by jasonLaster** [comment]
This has been fixed
